[package]
name = "java_grandine"
edition = { workspace = true }
authors = ["Grandine <info@grandine.io>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
runtime = { workspace = true, features = ["network-holesky"] }
directories = { workspace = true }
grandine_version = { workspace = true }
validator = { workspace = true }
fork_choice_control = { workspace = true }
fork_choice_store = { workspace = true }
eth1_api = { workspace = true }
signer = { workspace = true }
slashing_protection = { workspace = true }
http_api = { workspace = true }
slasher = { workspace = true }
anyhow = { workspace = true }
types = { workspace = true }
thiserror = { workspace = true }
reqwest = { workspace = true }
jni = "0.21.1"

[build-dependencies]
